if(NOT APP_FLASH_ORIGIN)
  set(PASSPRESS_RELOCATED_APP_ORIGIN "0x08002000")
  set(PASSPRESS_RELOCATED_APP_DIR "${CMAKE_BINARY_DIR}/relocated_app")
  set(PASSPRESS_RELOCATED_APP_STAMP "${PASSPRESS_RELOCATED_APP_DIR}/relocated_app.stamp")
  set(PASSPRESS_RELOCATED_APP_BUILD_CONFIG "${CMAKE_BUILD_TYPE}")

  if(NOT PASSPRESS_RELOCATED_APP_BUILD_CONFIG)
    set(PASSPRESS_RELOCATED_APP_BUILD_CONFIG Release)
  endif()

  add_custom_command(
    OUTPUT "${PASSPRESS_RELOCATED_APP_STAMP}"
    COMMAND "${CMAKE_COMMAND}" -E rm -rf "${PASSPRESS_RELOCATED_APP_DIR}"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${PASSPRESS_RELOCATED_APP_DIR}"
    COMMAND "${CMAKE_COMMAND}" -G Ninja -S "${CMAKE_SOURCE_DIR}" -B "${PASSPRESS_RELOCATED_APP_DIR}" -DCMAKE_TOOLCHAIN_FILE=${CMAKE_SOURCE_DIR}/cmake/gcc-arm-none-eabi.cmake -DAPP_FLASH_ORIGIN=${PASSPRESS_RELOCATED_APP_ORIGIN} -DLINKER_SCRIPT:FILEPATH=${PASSPRESS_RELOCATED_APP_DIR}/STM32F042XX_RELOCATED.ld -DCMAKE_BUILD_TYPE=${PASSPRESS_RELOCATED_APP_BUILD_CONFIG}
    COMMAND "${CMAKE_COMMAND}" --build "${PASSPRESS_RELOCATED_APP_DIR}"
    COMMAND "${CMAKE_COMMAND}" -E touch "${PASSPRESS_RELOCATED_APP_STAMP}"
    DEPENDS
      "${CMAKE_SOURCE_DIR}/CMakeLists.txt"
      "${CMAKE_SOURCE_DIR}/STM32F042XX_FLASH.ld"
      "${CMAKE_SOURCE_DIR}/cmake/gcc-arm-none-eabi.cmake"
      "${CMAKE_SOURCE_DIR}/cmake/stm32cubemx/CMakeLists.txt"
    VERBATIM
  )

  add_custom_target(relocated_app ALL DEPENDS "${PASSPRESS_RELOCATED_APP_STAMP}")
endif()